package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"social-media-api/internal/controller/graph/generated"
	"social-media-api/internal/models"
)

// Comments is the resolver for the comments field.
func (r *postResolver) Comments(ctx context.Context, obj *models.Post, limit *int, offset *int) ([]*models.Comment, error) {
	if *limit <= 0 || *offset < 0 {
		return nil, models.ErrIncorrectPaging
	}
	return r.CommentUseCase.GetMultiple(ctx, models.CommentFilter{PostID: obj.ID}, *limit, *offset)
}

// Post returns generated.PostResolver implementation.
func (r *Resolver) Post() generated.PostResolver { return &postResolver{r} }

type postResolver struct{ *Resolver }
