// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CommentInput struct {
	UserID int    `json:"userID"`
	PostID int    `json:"postID"`
	Body   string `json:"body"`
}

type Mutation struct {
}

type PostInput struct {
	UserID int    `json:"userID"`
	Body   string `json:"body"`
}

type Query struct {
}

type SubCommentInput struct {
	UserID   int    `json:"userID"`
	PostID   int    `json:"postID"`
	ParentID int    `json:"parentID"`
	Body     string `json:"body"`
}
