// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewPost struct {
	UserID int    `json:"userID"`
	Body   string `json:"body"`
}

type Query struct {
}
